### ISSUE TITLE
Moved Install Folder, no longer working

### ISSUE THREAD

**Issue by Zaazu** [db0/AI-Horde-Worker#156]
Hi,

I'm on Windows 11 and I moved the install folder and now it no longer works.
I've since deleted the whole folder and gone through the installation process again but it's still not working.

When I ran ```update-runtime.cmd``` the first time everything got set up correctly, and I was able to run the ```horde-bridge.cmd``` once, however, the next time it didn't work.

Running ```update-runtime.cmd``` again gives the following error:
```
                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

error    libmamba Non-conda folder exists at prefix
critical libmamba Aborting.
Traceback (most recent call last):
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\pip\__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\pip\_internal\cli\main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\pip\_internal\build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\pip\_internal\cli\spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\pip\_internal\utils\logging.py", line 4, in <module>
    import logging.handlers
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\logging\handlers.py", line 26, in <module>
    import io, logging, socket, os, pickle, struct, time, re
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\socket.py", line 54, in <module>
    import os, sys, io, selectors
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\selectors.py", line 12, in <module>
    import select
ModuleNotFoundError: No module named 'select'
If there are no errors above everything should be correctly installed (If not, try running update_runtime.cmd as admin).
```

Running ```horde-bridge.cmd``` again gives the following error:
```
The operation completed successfully.
Traceback (most recent call last):
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\bridge_stable_diffusion.py", line 10, in <module>
    from nataili.model_manager.super import ModelManager
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\model_manager\super.py", line 18, in <module>
    import torch
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\__init__.py", line 877, in <module>
    from torch import multiprocessing as multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\__init__.py", line 18, in <module>
    from .reductions import init_reductions
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\reductions.py", line 6, in <module>
    import multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\__init__.py", line 16, in <module>
    from . import context
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\context.py", line 6, in <module>
    from . import reduction
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\reduction.py", line 16, in <module>
    import socket
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\socket.py", line 54, in <module>
    import os, sys, io, selectors
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\selectors.py", line 12, in <module>
    import select
ModuleNotFoundError: No module named 'select'
The operation completed successfully.
Traceback (most recent call last):
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\bridge_stable_diffusion.py", line 10, in <module>
    from nataili.model_manager.super import ModelManager
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\model_manager\super.py", line 18, in <module>
    import torch
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\__init__.py", line 877, in <module>
    from torch import multiprocessing as multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\__init__.py", line 18, in <module>
    from .reductions import init_reductions
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\reductions.py", line 6, in <module>
    import multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\__init__.py", line 16, in <module>
    from . import context
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\context.py", line 6, in <module>
    from . import reduction
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\reduction.py", line 16, in <module>
    import socket
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\socket.py", line 54, in <module>
    import os, sys, io, selectors
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\selectors.py", line 12, in <module>
    import select
ModuleNotFoundError: No module named 'select'
The operation completed successfully.
Traceback (most recent call last):
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\bridge_stable_diffusion.py", line 10, in <module>
    from nataili.model_manager.super import ModelManager
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\model_manager\super.py", line 18, in <module>
    import torch
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\__init__.py", line 877, in <module>
    from torch import multiprocessing as multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\__init__.py", line 18, in <module>
    from .reductions import init_reductions
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\reductions.py", line 6, in <module>
    import multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\__init__.py", line 16, in <module>
    from . import context
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\context.py", line 6, in <module>
    from . import reduction
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\reduction.py", line 16, in <module>
    import socket
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\socket.py", line 54, in <module>
    import os, sys, io, selectors
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\selectors.py", line 12, in <module>
    import select
ModuleNotFoundError: No module named 'select'
The operation completed successfully.
Traceback (most recent call last):
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\bridge_stable_diffusion.py", line 10, in <module>
    from nataili.model_manager.super import ModelManager
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\model_manager\super.py", line 18, in <module>
    import torch
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\__init__.py", line 877, in <module>
    from torch import multiprocessing as multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\__init__.py", line 18, in <module>
    from .reductions import init_reductions
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\reductions.py", line 6, in <module>
    import multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\__init__.py", line 16, in <module>
    from . import context
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\context.py", line 6, in <module>
    from . import reduction
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\reduction.py", line 16, in <module>
    import socket
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\socket.py", line 54, in <module>
    import os, sys, io, selectors
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\selectors.py", line 12, in <module>
    import select
ModuleNotFoundError: No module named 'select'
The operation completed successfully.
Traceback (most recent call last):
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\bridge_stable_diffusion.py", line 10, in <module>
    from nataili.model_manager.super import ModelManager
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\model_manager\super.py", line 18, in <module>
    import torch
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\__init__.py", line 877, in <module>
    from torch import multiprocessing as multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\__init__.py", line 18, in <module>
    from .reductions import init_reductions
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\reductions.py", line 6, in <module>
    import multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\__init__.py", line 16, in <module>
    from . import context
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\context.py", line 6, in <module>
    from . import reduction
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\reduction.py", line 16, in <module>
    import socket
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\socket.py", line 54, in <module>
    import os, sys, io, selectors
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\selectors.py", line 12, in <module>
    import select
ModuleNotFoundError: No module named 'select'
The operation completed successfully.
Traceback (most recent call last):
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\bridge_stable_diffusion.py", line 10, in <module>
    from nataili.model_manager.super import ModelManager
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\model_manager\super.py", line 18, in <module>
    import torch
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\__init__.py", line 877, in <module>
    from torch import multiprocessing as multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\__init__.py", line 18, in <module>
    from .reductions import init_reductions
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\reductions.py", line 6, in <module>
    import multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\__init__.py", line 16, in <module>
    from . import context
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\context.py", line 6, in <module>
    from . import reduction
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\reduction.py", line 16, in <module>
    import socket
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\socket.py", line 54, in <module>
    import os, sys, io, selectors
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\selectors.py", line 12, in <module>
    import select
ModuleNotFoundError: No module named 'select'
The operation completed successfully.
Traceback (most recent call last):
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\bridge_stable_diffusion.py", line 10, in <module>
    from nataili.model_manager.super import ModelManager
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\model_manager\super.py", line 18, in <module>
    import torch
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\__init__.py", line 877, in <module>
    from torch import multiprocessing as multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\__init__.py", line 18, in <module>
    from .reductions import init_reductions
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\reductions.py", line 6, in <module>
    import multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\__init__.py", line 16, in <module>
    from . import context
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\context.py", line 6, in <module>
    from . import reduction
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\reduction.py", line 16, in <module>
    import socket
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\socket.py", line 54, in <module>
    import os, sys, io, selectors
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\selectors.py", line 12, in <module>
    import select
ModuleNotFoundError: No module named 'select'
The operation completed successfully.
Traceback (most recent call last):
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\bridge_stable_diffusion.py", line 10, in <module>
    from nataili.model_manager.super import ModelManager
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\model_manager\super.py", line 18, in <module>
    import torch
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\__init__.py", line 877, in <module>
    from torch import multiprocessing as multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\__init__.py", line 18, in <module>
    from .reductions import init_reductions
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\reductions.py", line 6, in <module>
    import multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\__init__.py", line 16, in <module>
    from . import context
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\context.py", line 6, in <module>
    from . import reduction
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\reduction.py", line 16, in <module>
    import socket
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\socket.py", line 54, in <module>
    import os, sys, io, selectors
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\selectors.py", line 12, in <module>
    import select
ModuleNotFoundError: No module named 'select'
The operation completed successfully.
Traceback (most recent call last):
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\bridge_stable_diffusion.py", line 10, in <module>
    from nataili.model_manager.super import ModelManager
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\model_manager\super.py", line 18, in <module>
    import torch
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\__init__.py", line 877, in <module>
    from torch import multiprocessing as multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\__init__.py", line 18, in <module>
    from .reductions import init_reductions
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\reductions.py", line 6, in <module>
    import multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\__init__.py", line 16, in <module>
    from . import context
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\context.py", line 6, in <module>
    from . import reduction
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\reduction.py", line 16, in <module>
    import socket
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\socket.py", line 54, in <module>
    import os, sys, io, selectors
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\selectors.py", line 12, in <module>
    import select
ModuleNotFoundError: No module named 'select'
The operation completed successfully.
Traceback (most recent call last):
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\bridge_stable_diffusion.py", line 10, in <module>
    from nataili.model_manager.super import ModelManager
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\model_manager\super.py", line 18, in <module>
    import torch
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\__init__.py", line 877, in <module>
    from torch import multiprocessing as multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\__init__.py", line 18, in <module>
    from .reductions import init_reductions
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\reductions.py", line 6, in <module>
    import multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\__init__.py", line 16, in <module>
    from . import context
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\context.py", line 6, in <module>
    from . import reduction
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\reduction.py", line 16, in <module>
    import socket
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\socket.py", line 54, in <module>
    import os, sys, io, selectors
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\selectors.py", line 12, in <module>
    import select
ModuleNotFoundError: No module named 'select'
The operation completed successfully.
Traceback (most recent call last):
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\bridge_stable_diffusion.py", line 10, in <module>
    from nataili.model_manager.super import ModelManager
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\model_manager\super.py", line 18, in <module>
    import torch
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\__init__.py", line 877, in <module>
    from torch import multiprocessing as multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\__init__.py", line 18, in <module>
    from .reductions import init_reductions
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\multiprocessing\reductions.py", line 6, in <module>
    import multiprocessing
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\__init__.py", line 16, in <module>
    from . import context
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\context.py", line 6, in <module>
    from . import reduction
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\multiprocessing\reduction.py", line 16, in <module>
    import socket
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\socket.py", line 54, in <module>
    import os, sys, io, selectors
  File "D:\Software\Stable Diffusion\AIHorde\AI-Horde-Worker\conda\envs\windows\lib\selectors.py", line 12, in <module>
    import select
ModuleNotFoundError: No module named 'select'
The operation completed successfully.

[process exited with code 3221226505 (0xc0000409)]
```

Any help is appreciated, thanks.

**Comment by db0** [comment]
What happens if you run `update-runtime.cmd`? 

Also generally discord is a better place for tech support
