### ISSUE TITLE
BUG: ModuleNotFoundError: No module named 'basicsr.ops'

### ISSUE THREAD

**Issue by Elijah629** [db0/AI-Horde-Worker#173]
**Issue**
When running the Stable Diffusion Bridge, I get the following error: ModuleNotFoundError: No module named 'basicsr.ops'

**Steps to reproduce**
1. Update Runtime
2. Configure
3. Run the Stable Diffusion Bridge

**Full Log**
```
Traceback (most recent call last):
  File "C:\Users\\Downloads\AI-Horde-Worker\bridge_stable_diffusion.py", line 70, in <module>
    main()
  File "C:\Users\\Downloads\AI-Horde-Worker\bridge_stable_diffusion.py", line 50, in main
    model_manager = ModelManager(
  File "C:\Users\\Downloads\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\model_manager\super.py", line 76, in __init__
    from nataili.model_manager.esrgan import EsrganModelManager
  File "C:\Users\\Downloads\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\model_manager\esrgan.py", line 22, in <module>
    from basicsr.archs.rrdbnet_arch import RRDBNet
  File "C:\Users\\Downloads\AI-Horde-Worker\conda\envs\windows\lib\site-packages\basicsr\__init__.py", line 3, in <module>
    from .archs import *
  File "C:\Users\\Downloads\AI-Horde-Worker\conda\envs\windows\lib\site-packages\basicsr\archs\__init__.py", line 16, in <module>
    _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
  File "C:\Users\\Downloads\AI-Horde-Worker\conda\envs\windows\lib\site-packages\basicsr\archs\__init__.py", line 16, in <listcomp>
    _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
  File "C:\Users\\Downloads\AI-Horde-Worker\conda\envs\windows\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\\Downloads\AI-Horde-Worker\conda\envs\windows\lib\site-packages\basicsr\archs\basicvsrpp_arch.py", line 7, in <module>
    from basicsr.archs.arch_util import flow_warp
  File "C:\Users\\Downloads\AI-Horde-Worker\conda\envs\windows\lib\site-packages\basicsr\archs\arch_util.py", line 13, in <module>
    from basicsr.ops.dcn import ModulatedDeformConvPack, modulated_deform_conv
ModuleNotFoundError: No module named 'basicsr.ops'
```

**Comment by db0** [comment]
did you run using the horde-bridge or directly with the python file?

**Comment by Elijah629** [comment]
horde-bridge, I'll try the python file though. It probably is running in a different environment without basics.

**Comment by db0** [comment]
No, it wouldn't run directly. I just weanted to make sure you were using horde-bridge

Maybe your runtime didn't update correctly. Try running update-runtime again

**Comment by Elijah629** [comment]
Still get the error.

**Comment by Elijah629** [comment]
I tried to run "pip install basicsr" and it worked.
I then tried
```
python
>>> import basicsr
```

and it does the error too

**Comment by Elijah629** [comment]
Fixed it, but it is still a bug. I had to make a batch file that installed and built BasicSR from source. I then ran that in umamba like this:
`.\umamba run -r conda -n windows .\file_i_made.cmd`

**Comment by Elijah629** [comment]
The file if anyone sees this
```cmd
cd path/to/basicsr
pip install -r requirements.txt
python setup.py develop
```

Clone basicsr with `git clone https://github.com/XPixelGroup/BasicSR.git`
