### ISSUE TITLE
binascii.Error: Invalid base64-encoded string: number of data characters (5) cannot be 1 more than a multiple of 4

### ISSUE THREAD

**Issue by wolfgangmeyers** [db0/AI-Horde-Worker#187]
Occasionally have the worker crash with this stack trace:

```
binascii.Error: Invalid base64-encoded string: number of data characters (5) cannot be 1 more than a multiple of 4
Traceback (most recent call last):
  File "/home/wolfgang/code/AI-Horde-Worker/bridge_stable_diffusion.py", line 70, in <module>
    main()
  File "/home/wolfgang/code/AI-Horde-Worker/bridge_stable_diffusion.py", line 62, in main
    worker.start()
  File "/home/wolfgang/code/AI-Horde-Worker/conda/envs/linux/lib/python3.10/site-packages/loguru/_logger.py", line 1251, in catch_wrapper
    return function(*args, **kwargs)
  File "/home/wolfgang/code/AI-Horde-Worker/worker/workers/framework.py", line 60, in start
    self.process_jobs()
  File "/home/wolfgang/code/AI-Horde-Worker/worker/workers/framework.py", line 77, in process_jobs
    self.add_job_to_queue()
  File "/home/wolfgang/code/AI-Horde-Worker/worker/workers/stable_diffusion.py", line 30, in add_job_to_queue
    job = super().add_job_to_queue()
  File "/home/wolfgang/code/AI-Horde-Worker/worker/workers/framework.py", line 97, in add_job_to_queue
    if jobs := self.pop_job():
  File "/home/wolfgang/code/AI-Horde-Worker/worker/workers/stable_diffusion.py", line 38, in pop_job
    return super().pop_job()
  File "/home/wolfgang/code/AI-Horde-Worker/worker/workers/framework.py", line 104, in pop_job
    pops = job_popper.horde_pop()
  File "/home/wolfgang/code/AI-Horde-Worker/worker/jobs/poppers.py", line 161, in horde_pop
    self.pop["source_image"] = self.download_source(self.pop.get("source_image"))
  File "/home/wolfgang/code/AI-Horde-Worker/worker/jobs/poppers.py", line 179, in download_source
    img_bytes = base64.b64decode(base64_bytes)
  File "/home/wolfgang/code/AI-Horde-Worker/conda/envs/linux/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (5) cannot be 1 more than a multiple of 4

```

**Comment by wolfgangmeyers** [comment]
Oddly this always seems to happen to all of my workers at the same time.

**Comment by db0** [comment]
Which branch are you in, `comfy` or `main`?

**Comment by wolfgangmeyers** [comment]
Main. Happy to switch over at this point

**Comment by db0** [comment]
yes, try `comfy` please as we won't be deploying fixes to the nataili version anymore.
