### ISSUE TITLE
Using controlnet + pix2pix sets workers into maintenance mode

### ISSUE THREAD

**Issue by AlRlC** [db0/AI-Horde-Worker#68]
Received a request for controlnet in conjunction with pix2pix, set my worker to maintenance.
pix2pix by itself works fine, just cant be combined 😅 

```
ERROR      | 2023-03-03 00:18:10.532211 | worker.jobs.stable_diffusion:start_job:325 - Something went wrong when processing request. Please check your trace.log file for the full stack trace. Payload: {'prompt': 'Hills with some snow on top', 'height': 960, 'width': 768, 'seed': '2509572726', 'tiling': False, 'n_iter': 1, 'batch_size': 1, 'save_individual_images': False, 'save_grid': False, 'ddim_steps': 30, 'sampler_name': 'k_euler_karras', 'cfg_scale': 7.0, 'denoising_strength': 0.75, 'control_type': 'canny', 'init_img': <PIL.Image.Image image mode=RGB size=768x960 at 0x1841D0AAD70>, 'request_type': 'img2img', 'model': 'pix2pix'}
TRACE      | 2023-03-03 00:18:10.534212 | worker.jobs.stable_diffusion:start_job:331 - Traceback (most recent call last):
  File "C:\Users\Airic\AI-Horde-Worker\worker\jobs\stable_diffusion.py", line 319, in start_job
    generator.generate(**gen_payload)
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\util\cast.py", line 29, in wrap
    return amp.autocast(device_type="cuda", dtype=dtype)(no_grad()(func))(*args, **kwargs)
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\amp\autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\stable_diffusion\compvis.py", line 307, in generate
    (self.control_net_model.control_model, "cpu"),
AttributeError: 'NoneType' object has no attribute 'control_model'
```

**Comment by jug-dev** [comment]
Probably fixed by https://github.com/db0/AI-Horde/commit/4765f7338de547c5db9fbff6e6c92fe27c8fce33

**Comment by db0** [comment]
Lol jug just stalking my commits :D
