### ISSUE TITLE
Unable to start `horde-bridge.sh` due to an error

### ISSUE THREAD

**Issue by AmdaUwU** [db0/AI-Horde-Worker#72]
When running `sh horde-bridge.sh` I get

``` sdout
INIT       | Checking    | xformers optimizations
INIT       | Loaded      | xformers optimizations
2023-03-03 18:33:38,789	INFO worker.py:1553 -- Started a local Ray instance.
INIT       | Prepared    | Ray temp dir '/home/amda/AI-Horde-Worker/ray'
INIT       | Downloading | Model Reference
INIT       | OK          | Model Reference
INFO       | 2023-03-03 18:34:07.269151 | nataili.model_manager.base:init:65 - Downloaded model reference. Got 167 models.
INFO       | 2023-03-03 18:34:07.271257 | nataili.model_manager.base:init:77 - Got 0 available models.
Traceback (most recent call last):
  File "/home/amda/AI-Horde-Worker/bridge_stable_diffusion.py", line 66, in <module>
    main()
  File "/home/amda/AI-Horde-Worker/bridge_stable_diffusion.py", line 47, in main
    model_manager = ModelManager(
  File "/home/amda/AI-Horde-Worker/conda/envs/linux/lib/python3.10/site-packages/nataili/model_manager/super.py", line 68, in __init__
    from nataili.model_manager.diffusers import DiffusersModelManager
  File "/home/amda/AI-Horde-Worker/conda/envs/linux/lib/python3.10/site-packages/nataili/model_manager/diffusers.py", line 22, in <module>
    from diffusers.pipelines import StableDiffusionDepth2ImgPipeline, StableDiffusionInpaintPipeline
ImportError: cannot import name 'StableDiffusionDepth2ImgPipeline' from 'diffusers.pipelines' (/home/amda/.local/lib/python3.10/site-packages/diffusers/pipelines/__init__.py)
```

This might be my error as I have not gave model checkpoint or a hugging face api key. I am not sure how I am supposed to ass these?

**Comment by db0** [comment]
have you run update-runtime.sh?

Generally it's better to come to our discord for support like this as there's more people able to help

**Comment by ronjon469** [comment]
Discord link? Similar issue just different error

**Comment by jug-dev** [comment]
Closing this as assuming the op has gone to discord, please reopen if required.
